Sponsor page updated
OSDLabs/WavesWebsite2016 pull request #34
Opened 2016-10-12 11:03 UTC by AkhilKamath

2016-10-13 14:34 UTC, SebastinSanty requested changes
Other than these, all looks good :)

2016-10-13 14:34 UTC, SebastinSanty commented on sponsors/views.py
> +			"spons_category" : cat,
cat should only contain 'Title Sponsor' if there are objects under 'Title Sponsor'. If there are sponsors in a particular category, it shouldn't show up on the page.

2016-10-13 14:34 UTC, SebastinSanty commented on sponsors/models.py
> +	sponsURL = models.URLField(max_length=200, default="add sponsor's webpage")
Need not be a required field. Put `blank=True`.

2016-10-13 15:47 UTC, mukkachaitanya commented
I tried to apply the patch and encountered errors while entering `/admin`.
```
Environment:


Request Method: GET
Request URL: http://139.59.19.146:8000/accounts/register/

Django Version: 1.8
Python Version: 2.7.9
Installed Applications:
('django.contrib.admin',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'crispy_forms',
 'django.contrib.sites',
 'registration',
 'rest_framework',
 'push_notifications',
 'django.contrib.auth',
 'home',
 'wavesprofile',
 'accommodation',
 'events',
 'team',
 'sponsors')
Installed Middleware:
('django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware')


Template error:
In template /home/mukka/waves/src/templates/registration/registration_form.html, error at line 24
   No module named reportlab.pdfgen

   14 : <form method="post" action=".">



   15 :   {% csrf_token %}



   16 :   {{ form|crispy }}



   17 : 



   18 :   <input class='btn btn-block btn-primary' type="submit" value="{% trans 'Register' %}" />



   19 : </form>



   20 : 



   21 : 



   22 : <hr/>



   23 : 



   24 : <p>Need to <a href=" {% url 'auth_login' %} ">Login</a>?</p>



   25 : <p>{% trans "Go to Home" %}: <a href="{% url 'home' %}">{% trans "Home" %}</a></p>



   26 : 



   27 : 



   28 : 



   29 : {% endblock %}



   30 : 

Traceback:
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  164.                 response = response.render()
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/template/response.py" in render
  158.             self.content = self.rendered_content
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/template/response.py" in rendered_content
  135.         content = template.render(context, self._request)
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/template/backends/django.py" in render
  74.         return self.template.render(context)
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/template/base.py" in render
  209.                     return self._render(context)
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/template/base.py" in _render
  201.         return self.nodelist.render(context)
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/template/base.py" in render
  903.                 bit = self.render_node(node, context)
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/template/debug.py" in render_node
  79.             return node.render(context)
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/template/loader_tags.py" in render
  135.         return compiled_parent._render(context)
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/template/base.py" in _render
  201.         return self.nodelist.render(context)
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/template/base.py" in render
  903.                 bit = self.render_node(node, context)
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/template/debug.py" in render_node
  79.             return node.render(context)
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/template/loader_tags.py" in render
  65.                 result = block.nodelist.render(context)
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/template/base.py" in render
  903.                 bit = self.render_node(node, context)
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/template/debug.py" in render_node
  79.             return node.render(context)
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/template/defaulttags.py" in render
  493.             url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/core/urlresolvers.py" in reverse
  579.     return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/core/urlresolvers.py" in _reverse_with_prefix
  433.             self._populate()
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/core/urlresolvers.py" in _populate
  326.                 lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/core/urlresolvers.py" in callback
  247.         self._callback = get_callable(self._callback_str)
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/utils/lru_cache.py" in wrapper
  101.                     result = user_function(*args, **kwds)
File "/home/mukka/waves/local/lib/python2.7/site-packages/django/core/urlresolvers.py" in get_callable
  106.         mod = import_module(mod_name)
File "/usr/lib/python2.7/importlib/__init__.py" in import_module
  37.     __import__(name)
File "/home/mukka/waves/src/print/views.py" in <module>
  2. from reportlab.pdfgen import canvas

Exception Type: ImportError at /accounts/register/
Exception Value: No module named reportlab.pdfgen
```

2016-10-13 16:38 UTC, SebastinSanty commented
@mukkachaitanya Maybe you don't have reportlab installed in your virtualenv

2026-01-22 18:58 UTC, closed without merging

2026-01-22 22:08 UTC, SebastinSanty commented
Thanks everybody!

2026-01-23 00:05 UTC, AkhilKamath commented
You're welcome!